name: "Glue: build and test"
on: [push]

jobs:
  cargo_crate:
    name: Build Rust crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo publish --dry-run
        working-directory: glue/rust

  npm_package:
    name: Build AS package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: npm publish --dry-run
        run: |
          npm install
          npm publish --dry-run
        working-directory: glue/assemblyscript
